"""create travel tables

Revision ID: c8ac766d5800
Revises: 46df54a0184f
Create Date: 2026-05-05 04:44:11.067361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8ac766d5800'
down_revision: Union[str, Sequence[str], None] = '46df54a0184f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='行程标题'),
    sa.Column('location', sa.String(length=100), nullable=False, comment='目的地'),
    sa.Column('days', sa.Integer(), nullable=False, comment='旅行天数'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='用户偏好列表'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'planning'"), nullable=False, comment='行程状态: planning/completed/failed/deleted'),
    sa.Column('latest_version_no', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='最新版本号'),
    sa.Column('thread_id', sa.String(length=80), nullable=True, comment='创建或最近一次修改使用的线程ID'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='规划失败原因'),
    sa.Column('id', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.CheckConstraint("status in ('planning', 'completed', 'failed', 'deleted')", name=op.f('ck_trips_trip_status')),
    sa.CheckConstraint('days >= 1', name=op.f('ck_trips_trip_days_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    comment='行程主表'
    )
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_thread_id'), 'trips', ['thread_id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_index('ix_trips_user_status_updated', 'trips', ['user_id', 'status', 'updated_at'], unique=False)
    op.create_table('trip_versions',
    sa.Column('trip_id', sa.String(length=64), nullable=False, comment='行程ID'),
    sa.Column('version_no', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'initial'"), nullable=False, comment='版本来源: initial/revision'),
    sa.Column('revision_instruction', sa.Text(), nullable=True, comment='修改指令'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='行程内容JSON'),
    sa.Column('id', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("source in ('initial', 'revision')", name=op.f('ck_trip_versions_trip_version_source')),
    sa.CheckConstraint('version_no >= 1', name=op.f('ck_trip_versions_trip_version_no_positive')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_versions_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_versions')),
    sa.UniqueConstraint('trip_id', 'version_no', name='uq_trip_versions_trip_version_no'),
    comment='行程版本表'
    )
    op.create_index('ix_trip_versions_trip_created', 'trip_versions', ['trip_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_trip_versions_trip_id'), 'trip_versions', ['trip_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('trip_id', sa.String(length=64), nullable=False, comment='行程ID'),
    sa.Column('trip_version_id', sa.String(length=64), nullable=True, comment='关联行程版本ID'),
    sa.Column('thread_id', sa.String(length=80), nullable=True, comment='线程ID'),
    sa.Column('agent_name', sa.String(length=50), nullable=False, comment='智能体名称'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='执行状态'),
    sa.Column('input_summary', sa.Text(), nullable=True, comment='输入摘要'),
    sa.Column('output_summary', sa.Text(), nullable=True, comment='输出摘要'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('id', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status in ('pending', 'running', 'completed', 'failed')", name=op.f('ck_agent_runs_agent_run_status')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_agent_runs_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_version_id'], ['trip_versions.id'], name=op.f('fk_agent_runs_trip_version_id_trip_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    comment='智能体执行记录表'
    )
    op.create_index(op.f('ix_agent_runs_thread_id'), 'agent_runs', ['thread_id'], unique=False)
    op.create_index('ix_agent_runs_trip_agent_created', 'agent_runs', ['trip_id', 'agent_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_trip_id'), 'agent_runs', ['trip_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_trip_version_id'), 'agent_runs', ['trip_version_id'], unique=False)
    op.create_table('tool_call_logs',
    sa.Column('agent_run_id', sa.String(length=64), nullable=False, comment='智能体执行记录ID'),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='调用状态'),
    sa.Column('request_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具请求参数'),
    sa.Column('response_summary', sa.Text(), nullable=True, comment='响应摘要'),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='响应原始内容'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='调用耗时，毫秒'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status in ('pending', 'running', 'completed', 'failed')", name=op.f('ck_tool_call_logs_tool_call_log_status')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_tool_call_logs_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_call_logs')),
    comment='工具调用日志表'
    )
    op.create_index('ix_tool_call_logs_agent_created', 'tool_call_logs', ['agent_run_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_agent_run_id'), 'tool_call_logs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_tool_name'), 'tool_call_logs', ['tool_name'], unique=False)
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_table('checkpoint_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_tool_call_logs_tool_name'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_agent_run_id'), table_name='tool_call_logs')
    op.drop_index('ix_tool_call_logs_agent_created', table_name='tool_call_logs')
    op.drop_table('tool_call_logs')
    op.drop_index(op.f('ix_agent_runs_trip_version_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_trip_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_trip_agent_created', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_thread_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_trip_versions_trip_id'), table_name='trip_versions')
    op.drop_index('ix_trip_versions_trip_created', table_name='trip_versions')
    op.drop_table('trip_versions')
    op.drop_index('ix_trips_user_status_updated', table_name='trips')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_thread_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
